# Generated by Django 4.1.7 on 2023-03-09 01:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'First name must be greater than 1 character')])),
                ('last', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'First name must be greater than 1 character')])),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField(auto_now_add=True)),
                ('checkin_time', models.TimeField(auto_now_add=True)),
                ('process_date', models.DateField(blank=True, null=True)),
                ('contact_date', models.DateTimeField(blank=True, null=True)),
                ('sausage_taken', models.BooleanField(blank=True, null=True)),
                ('processing_cost', models.IntegerField(blank=True, default=75)),
                ('smoked_cost', models.FloatField(blank=True, default=0)),
                ('bulk_cost', models.FloatField(blank=True, default=0)),
                ('tag_number', models.CharField(max_length=20)),
                ('Gender', models.CharField(choices=[('Doe', 'Doe'), ('Buck', 'Buck')], default='doe', max_length=4)),
                ('Mount', models.CharField(blank=True, choices=[('Antlers', 'Antler Mount'), ('Euro', 'Euro Mount'), ('Shoulder', 'Shoulder Mount')], max_length=8)),
                ('Hide', models.CharField(blank=True, choices=[('Yes', 'Keep Hide ($10)')], max_length=4)),
                ('Loins', models.CharField(choices=[('Steaks', 'Steaks'), ('Whole', 'Whole'), ('Burger', 'Burger')], default='Steaks', max_length=6)),
                ('Tender_Loins', models.CharField(choices=[('Steaks', 'Steaks'), ('Whole', 'Whole'), ('Burger', 'Burger')], default='Steaks', max_length=6)),
                ('Rounds', models.CharField(choices=[('Steaks', 'Steaks'), ('Whole', 'Whole'), ('Burger', 'Burger')], default='Steaks', max_length=6)),
                ('Tips', models.CharField(choices=[('Steaks', 'Steaks'), ('Whole', 'Whole'), ('Burger', 'Burger')], default='Steaks', max_length=6)),
                ('Burger', models.CharField(choices=[('Ground', 'Ground Burger'), ('All Sausage', 'All Sausage')], default='Ground', max_length=11)),
                ('Shoulder_roast', models.CharField(choices=[('0', 'None'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('All', 'All')], default='0', max_length=3)),
                ('Neck_Roast', models.CharField(choices=[('0', 'None'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('All', 'All')], default='0', max_length=3)),
                ('Package_Size', models.FloatField(choices=[(0.5, '1/2 lb'), (1, '1 lb'), (1.5, '1 1/2 lb'), (2, '2 lb'), (2.5, '2 1/2lb'), (3, '3 lb')], default=1, max_length=3)),
                ('Notes', models.TextField(blank=True)),
                ('payment_style', models.CharField(blank=True, choices=[('none', 'Not Paid'), ('cash', 'Cash'), ('credit', 'Credit'), ('check', 'Check'), ('free', 'Free')], default='none', max_length=6)),
                ('process_paid', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer')),
            ],
        ),
        migrations.CreateModel(
            name='SausageOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Original_Summer_Sausage', models.CharField(blank=True, choices=[('0', 'None'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('All', 'All')], max_length=3, null=True)),
                ('Cheese_Summer_Sausage', models.CharField(blank=True, choices=[('0', 'None'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('All', 'All')], max_length=3, null=True)),
                ('Jalap_Summer_Sausage', models.CharField(blank=True, choices=[('0', 'None'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('All', 'All')], max_length=3, null=True)),
                ('Hickory_Stick', models.CharField(blank=True, choices=[('0', 'None'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('All', 'All')], max_length=3, null=True)),
                ('Original_Pepper_Sticks', models.CharField(blank=True, choices=[('0', 'None'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('All', 'All')], max_length=3, null=True)),
                ('Jalapeno_Cheese_Pepper_Sticks', models.CharField(blank=True, choices=[('0', 'None'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('All', 'All')], max_length=3, null=True)),
                ('Hunter_Twiggs', models.CharField(blank=True, choices=[('0', 'None'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('All', 'All')], max_length=3, null=True)),
                ('Honey_BBQ_Pepper_Sticks', models.CharField(blank=True, choices=[('0', 'None'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('All', 'All')], max_length=3, null=True)),
                ('Smoked_Brats', models.CharField(blank=True, choices=[('0', 'None'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('All', 'All')], max_length=3, null=True)),
                ('Jalapeno_Smoked_Brats', models.CharField(blank=True, choices=[('0', 'None'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('All', 'All')], max_length=3, null=True)),
                ('smoked_ham', models.IntegerField(blank=True, choices=[('1', 'One'), ('2', 'Two')], null=True)),
                ('jerky', models.IntegerField(blank=True, null=True)),
                ('jerky_sweet_and_spicy', models.IntegerField(blank=True, null=True)),
                ('maple_breakfast', models.CharField(blank=True, choices=[('3', '3 lbs'), ('6', '6 lbs'), ('9', '9 lbs'), ('All', 'All')], max_length=3, null=True)),
                ('spicy_breakfast', models.CharField(blank=True, choices=[('3', '3 lbs'), ('6', '6 lbs'), ('9', '9 lbs'), ('All', 'All')], max_length=3, null=True)),
                ('italian', models.CharField(blank=True, choices=[('3', '3 lbs'), ('6', '6 lbs'), ('9', '9 lbs'), ('All', 'All')], max_length=3, null=True)),
                ('sausage_paid', models.BooleanField(default=False)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
