# Generated by Django 4.1.7 on 2023-03-13 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=50)),
                ('last', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sausage_out', models.BooleanField(blank=True, default=False, null=True)),
                ('bulk_out', models.BooleanField(blank=True, default=False, null=True)),
                ('ham_out', models.BooleanField(blank=True, default=False, null=True)),
                ('jerky_out', models.BooleanField(blank=True, default=False, null=True)),
                ('freezer', models.IntegerField(null=True)),
                ('bag', models.IntegerField(null=True)),
                ('contact_date', models.DateTimeField(blank=True, null=True)),
                ('sausage_ordered', models.BooleanField(blank=True, null=True)),
                ('order_gone', models.BooleanField(blank=True, default=False, null=True)),
                ('sausage_gone', models.BooleanField(blank=True, default=False, null=True)),
                ('process_paid', models.BooleanField(default=False, null=True)),
                ('sausage_paid', models.BooleanField(default=False, null=True)),
                ('checkout_date', models.DateTimeField(blank=True, null=True)),
                ('sausage_date', models.DateTimeField(blank=True, null=True)),
                ('payment_style', models.CharField(blank=True, choices=[('None', 'Not Paid'), ('Cash', 'Cash'), ('Credit', 'Credit'), ('Check', 'Check'), ('Free', 'Free')], max_length=6)),
                ('hide_cost', models.IntegerField(blank=True, default=0)),
                ('sausage_cost', models.FloatField(blank=True, default=0)),
                ('smoked_cost', models.FloatField(blank=True, default=0)),
                ('bulk_cost', models.FloatField(blank=True, default=0)),
                ('process_cost', models.IntegerField(blank=True)),
                ('total_cost', models.FloatField(blank=True)),
                ('process_date', models.DateTimeField(blank=True, null=True)),
                ('checkin_date', models.DateField(auto_now_add=True)),
                ('checkin_time', models.TimeField(auto_now_add=True)),
                ('tag_number', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Doe', 'Doe'), ('Buck', 'Buck')], default='doe', max_length=4)),
                ('points', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16)], null=True)),
                ('mount', models.CharField(blank=True, choices=[('Antlers', 'Antler Mount'), ('Euro', 'Euro Mount'), ('Shoulder', 'Shoulder Mount')], max_length=8, null=True)),
                ('hide', models.CharField(blank=True, choices=[('Yes', 'Keep Hide ($10)')], max_length=4, null=True)),
                ('loins', models.CharField(choices=[('Steaks', 'Steaks'), ('Whole', 'Whole'), ('Burger', 'Burger')], default='Steaks', max_length=6)),
                ('tender_loins', models.CharField(choices=[('Steaks', 'Steaks'), ('Whole', 'Whole'), ('Burger', 'Burger'), ('Removed', 'Removed')], default='Steaks', max_length=7)),
                ('rounds', models.CharField(choices=[('Steaks', 'Steaks'), ('Whole', 'Whole'), ('Burger', 'Burger')], default='Steaks', max_length=6)),
                ('tips', models.CharField(choices=[('Steaks', 'Steaks'), ('Whole', 'Whole'), ('Burger', 'Burger')], default='Steaks', max_length=6)),
                ('burger', models.CharField(choices=[('Ground', 'Ground Burger'), ('Sausage', 'All Sausage')], default='Ground', max_length=11)),
                ('shoulder_roast', models.CharField(blank=True, choices=[('', 'None'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('All', 'All')], max_length=3, null=True)),
                ('neck_roast', models.CharField(blank=True, choices=[('', 'None'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('All', 'All')], max_length=3, null=True)),
                ('package_size', models.CharField(choices=[('1/2 lb', '1/2 lb'), ('1 lb', '1 lb'), ('1 1/2 lb', '1 1/2 lb'), ('2 lb', '2 lb'), ('2 1/2lb', '2 1/2lb'), ('3 lb', '3 lb')], default='1 lb', max_length=8)),
                ('notes', models.TextField(blank=True, null=True)),
                ('smoked_lbs', models.IntegerField(blank=True, null=True)),
                ('original_summer_sausage', models.CharField(blank=True, choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('All', 'All')], max_length=3, null=True)),
                ('cheese_summer_sausage', models.CharField(blank=True, choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('All', 'All')], max_length=3, null=True)),
                ('jalapeno_summer_sausage', models.CharField(blank=True, choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('All', 'All')], max_length=3, null=True)),
                ('hickory_stick', models.CharField(blank=True, choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('All', 'All')], max_length=3, null=True)),
                ('original_pepper_sticks', models.CharField(blank=True, choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('All', 'All')], max_length=3, null=True)),
                ('jalapeno_pepper_sticks', models.CharField(blank=True, choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('All', 'All')], max_length=3, null=True)),
                ('hunter_twiggs', models.CharField(blank=True, choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('All', 'All')], max_length=3, null=True)),
                ('honey_bbq_pepper_sticks', models.CharField(blank=True, choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('All', 'All')], max_length=3, null=True)),
                ('smoked_brats', models.CharField(blank=True, choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('All', 'All')], max_length=3, null=True)),
                ('jalapeno_smoked_brats', models.CharField(blank=True, choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('All', 'All')], max_length=3, null=True)),
                ('jerky_lbs', models.IntegerField(blank=True, null=True)),
                ('smoked_ham', models.IntegerField(blank=True, choices=[(1, 'One'), (2, 'Two')], null=True)),
                ('jerky', models.CharField(blank=True, choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('All', 'All')], max_length=3, null=True)),
                ('jerky_sweet_and_spicy', models.CharField(blank=True, choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('All', 'All')], max_length=3, null=True)),
                ('bulk_lbs', models.FloatField(blank=True, null=True)),
                ('maple_breakfast', models.CharField(blank=True, choices=[('3', '3 lbs'), ('6', '6 lbs'), ('9', '9 lbs'), ('All', 'All')], max_length=3, null=True)),
                ('spicy_breakfast', models.CharField(blank=True, choices=[('3', '3 lbs'), ('6', '6 lbs'), ('9', '9 lbs'), ('All', 'All')], max_length=3, null=True)),
                ('italian', models.CharField(blank=True, choices=[('3', '3 lbs'), ('6', '6 lbs'), ('9', '9 lbs'), ('All', 'All')], max_length=3, null=True)),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.customer')),
            ],
        ),
    ]
