# Generated by Django 4.1.7 on 2023-03-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tender_Loins',
            new_name='tender_loins',
        ),
    ]
