# Generated by Django 4.1.7 on 2023-03-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_gone',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='saugsage_gone',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='sausage_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='bulk_cost',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='hide_cost',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='process_cost',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sausage_cost',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='smoked_cost',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
