# Generated by Django 4.1.7 on 2023-03-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='smoked_cost',
        ),
        migrations.AddField(
            model_name='order',
            name='Cheese_Summer_Sausage',
            field=models.CharField(blank=True, choices=[(0, 'None'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), ('All', 'All')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Hickory_Stick',
            field=models.CharField(blank=True, choices=[(0, 'None'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), ('All', 'All')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Honey_BBQ_Pepper_Sticks',
            field=models.CharField(blank=True, choices=[(0, 'None'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), ('All', 'All')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Hunter_Twiggs',
            field=models.CharField(blank=True, choices=[(0, 'None'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), ('All', 'All')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Jalap_Summer_Sausage',
            field=models.CharField(blank=True, choices=[(0, 'None'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), ('All', 'All')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Jalapeno_Cheese_Pepper_Sticks',
            field=models.CharField(blank=True, choices=[(0, 'None'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), ('All', 'All')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Jalapeno_Smoked_Brats',
            field=models.CharField(blank=True, choices=[(0, 'None'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), ('All', 'All')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Original_Pepper_Sticks',
            field=models.CharField(blank=True, choices=[(0, 'None'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), ('All', 'All')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Original_Summer_Sausage',
            field=models.CharField(blank=True, choices=[(0, 'None'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), ('All', 'All')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Points',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16)], default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='Smoked_Brats',
            field=models.CharField(blank=True, choices=[(0, 'None'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), ('All', 'All')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='italian',
            field=models.CharField(blank=True, choices=[('3', '3 lbs'), ('6', '6 lbs'), ('9', '9 lbs'), ('All', 'All')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='jerky',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), ('All', 'All')], null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='jerky_sweet_and_spicy',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), ('All', 'All')], null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='maple_breakfast',
            field=models.CharField(blank=True, choices=[('3', '3 lbs'), ('6', '6 lbs'), ('9', '9 lbs'), ('All', 'All')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sausage_cost',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='sausage_ordered',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sausage_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='smoked_ham',
            field=models.IntegerField(blank=True, choices=[('1', 'One'), ('2', 'Two')], null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='spicy_breakfast',
            field=models.CharField(blank=True, choices=[('3', '3 lbs'), ('6', '6 lbs'), ('9', '9 lbs'), ('All', 'All')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Neck_Roast',
            field=models.CharField(choices=[(0, 'None'), (1, 'One'), (2, 'Two'), (3, 'Three'), ('All', 'All')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='Shoulder_roast',
            field=models.CharField(choices=[(0, 'None'), (1, 'One'), (2, 'Two'), (3, 'Three'), ('All', 'All')], default='0', max_length=3),
        ),
        migrations.DeleteModel(
            name='SausageOrder',
        ),
    ]
