# Generated by Django 4.1.7 on 2023-03-09 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_tender_loins_order_tender_loins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='jalap_summer_sausage',
            new_name='jalapeno_summer_sausage',
        ),
    ]
