# Generated by Django 4.1.7 on 2023-03-11 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_gone_order_saugsage_gone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='saugsage_gone',
            new_name='sausage_gone',
        ),
    ]
