# Generated by Django 4.1.7 on 2023-03-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_saugsage_gone_order_sausage_gone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_gone',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='process_paid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sausage_gone',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sausage_paid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
