# Generated by Django 4.1.7 on 2023-03-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_order_gone_alter_order_process_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bulk_out',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ham_out',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='jerky_out',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sausage_out',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
